// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as SeedBankProcedure from "../seed_bank_procedure";

export type SeedBankArgs = __Infer<typeof SeedBankProcedure.params>;
export type SeedBankResult = __Infer<typeof SeedBankProcedure.returnType>;

