// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptReducer from "../accept_reducer";
import ConfirmDeliveryReducer from "../confirm_delivery_reducer";
import CreateListingReducer from "../create_listing_reducer";
import DeclineReducer from "../decline_reducer";
import DemoFastForwardReducer from "../demo_fast_forward_reducer";
import DemoResetReducer from "../demo_reset_reducer";
import JoinReducer from "../join_reducer";
import MarkPaymentHeldReducer from "../mark_payment_held_reducer";
import MarkRefundedReducer from "../mark_refunded_reducer";
import MarkReleasedReducer from "../mark_released_reducer";
import MarkShippedReducer from "../mark_shipped_reducer";
import SetConfigReducer from "../set_config_reducer";
import StartDealReducer from "../start_deal_reducer";

export type AcceptParams = __Infer<typeof AcceptReducer>;
export type ConfirmDeliveryParams = __Infer<typeof ConfirmDeliveryReducer>;
export type CreateListingParams = __Infer<typeof CreateListingReducer>;
export type DeclineParams = __Infer<typeof DeclineReducer>;
export type DemoFastForwardParams = __Infer<typeof DemoFastForwardReducer>;
export type DemoResetParams = __Infer<typeof DemoResetReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type MarkPaymentHeldParams = __Infer<typeof MarkPaymentHeldReducer>;
export type MarkRefundedParams = __Infer<typeof MarkRefundedReducer>;
export type MarkReleasedParams = __Infer<typeof MarkReleasedReducer>;
export type MarkShippedParams = __Infer<typeof MarkShippedReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type StartDealParams = __Infer<typeof StartDealReducer>;

