// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CancelPaymentReducer from "../cancel_payment_reducer";
import ConfirmPaymentReducer from "../confirm_payment_reducer";
import CreateListingReducer from "../create_listing_reducer";
import DemoFastForwardReducer from "../demo_fast_forward_reducer";
import DemoResetReducer from "../demo_reset_reducer";
import JoinReducer from "../join_reducer";
import ObjectionElapsedReducer from "../objection_elapsed_reducer";
import OnConnectReducer from "../on_connect_reducer";
import OnDisconnectReducer from "../on_disconnect_reducer";
import PausePaymentReducer from "../pause_payment_reducer";
import ReleasePaymentReducer from "../release_payment_reducer";
import RequestPaymentReducer from "../request_payment_reducer";
import SetConfigReducer from "../set_config_reducer";
import StopPaymentReducer from "../stop_payment_reducer";
import TimeoutPaymentReducer from "../timeout_payment_reducer";

export type CancelPaymentParams = __Infer<typeof CancelPaymentReducer>;
export type ConfirmPaymentParams = __Infer<typeof ConfirmPaymentReducer>;
export type CreateListingParams = __Infer<typeof CreateListingReducer>;
export type DemoFastForwardParams = __Infer<typeof DemoFastForwardReducer>;
export type DemoResetParams = __Infer<typeof DemoResetReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type ObjectionElapsedParams = __Infer<typeof ObjectionElapsedReducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>;
export type PausePaymentParams = __Infer<typeof PausePaymentReducer>;
export type ReleasePaymentParams = __Infer<typeof ReleasePaymentReducer>;
export type RequestPaymentParams = __Infer<typeof RequestPaymentReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type StopPaymentParams = __Infer<typeof StopPaymentReducer>;
export type TimeoutPaymentParams = __Infer<typeof TimeoutPaymentReducer>;

