// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  listingId: __t.u64().name("listing_id"),
  buyerId: __t.identity().name("buyer_id"),
  sellerId: __t.identity().name("seller_id"),
  status: __t.string(),
  round: __t.u32(),
  bidCents: __t.u64().name("bid_cents"),
  askCents: __t.u64().name("ask_cents"),
  priceCents: __t.option(__t.u64()).name("price_cents"),
  buyerAccepted: __t.bool().name("buyer_accepted"),
  sellerAccepted: __t.bool().name("seller_accepted"),
  shipByAt: __t.option(__t.u64()).name("ship_by_at"),
  tracking: __t.option(__t.string()),
  holdTransferId: __t.option(__t.string()).name("hold_transfer_id"),
  releaseTransferId: __t.option(__t.string()).name("release_transfer_id"),
  refundTransferId: __t.option(__t.string()).name("refund_transfer_id"),
  createdAt: __t.u64().name("created_at"),
});
