// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nameKey: __t.string().primaryKey().name("name_key"),
  nessieAccountId: __t.string().name("nessie_account_id"),
  score: __t.u32(),
  reasonsJson: __t.string().name("reasons_json"),
  knownBiller: __t.bool().name("known_biller"),
  momBalanceCents: __t.u64().name("mom_balance_cents"),
  updatedAt: __t.u64().name("updated_at"),
});
