// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  elderId: __t.identity().name("elder_id"),
  payeeName: __t.string().name("payee_name"),
  payeeNessieId: __t.option(__t.string()).name("payee_nessie_id"),
  amountCents: __t.u64().name("amount_cents"),
  score: __t.u32(),
  reasonsJson: __t.string().name("reasons_json"),
  status: __t.string(),
  secretFlag: __t.bool().name("secret_flag"),
  paidBy: __t.option(__t.identity()).name("paid_by"),
  pausedBy: __t.option(__t.identity()).name("paused_by"),
  stoppedBy: __t.option(__t.string()).name("stopped_by"),
  transferId: __t.option(__t.string()).name("transfer_id"),
  createdAt: __t.u64().name("created_at"),
  round: __t.u32(),
  momRound: __t.u32().name("mom_round"),
  approveRound: __t.u32().name("approve_round"),
  approvedBy: __t.option(__t.identity()).name("approved_by"),
  windowRound: __t.u32().name("window_round"),
});
