// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  slot: __t.string(),
  label: __t.string(),
  nessieAccountId: __t.string(),
  balanceCents: __t.u64(),
});
export type Account = __Infer<typeof Account>;

export const AuditEvent = __t.object("AuditEvent", {
  id: __t.u64(),
  text: __t.string(),
  at: __t.u64(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const HoldTimer = __t.object("HoldTimer", {
  id: __t.u64(),
  paymentId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HoldTimer = __Infer<typeof HoldTimer>;

export const Listing = __t.object("Listing", {
  id: __t.u64(),
  sellerId: __t.identity(),
  title: __t.string(),
  emoji: __t.string(),
  listCents: __t.u64(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Listing = __Infer<typeof Listing>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  name: __t.string(),
  role: __t.string(),
  slot: __t.string(),
  online: __t.bool(),
});
export type Member = __Infer<typeof Member>;

export const MyLimit = __t.object("MyLimit", {
  kind: __t.string(),
  cents: __t.u64(),
});
export type MyLimit = __Infer<typeof MyLimit>;

export const MyLimits = __t.object("MyLimits", {});
export type MyLimits = __Infer<typeof MyLimits>;

export const NessieLog = __t.object("NessieLog", {
  id: __t.u64(),
  method: __t.string(),
  path: __t.string(),
  status: __t.u32(),
  note: __t.string(),
  at: __t.u64(),
});
export type NessieLog = __Infer<typeof NessieLog>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  paymentId: __t.u64(),
  kind: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type Outbox = __Infer<typeof Outbox>;

export const PayeeCache = __t.object("PayeeCache", {
  nameKey: __t.string(),
  nessieAccountId: __t.string(),
  score: __t.u32(),
  reasonsJson: __t.string(),
  knownBiller: __t.bool(),
  momBalanceCents: __t.u64(),
  updatedAt: __t.u64(),
});
export type PayeeCache = __Infer<typeof PayeeCache>;

export const Payment = __t.object("Payment", {
  id: __t.u64(),
  elderId: __t.identity(),
  payeeName: __t.string(),
  payeeNessieId: __t.option(__t.string()),
  amountCents: __t.u64(),
  score: __t.u32(),
  reasonsJson: __t.string(),
  status: __t.string(),
  secretFlag: __t.bool(),
  paidBy: __t.option(__t.identity()),
  pausedBy: __t.option(__t.identity()),
  stoppedBy: __t.option(__t.string()),
  transferId: __t.option(__t.string()),
  createdAt: __t.u64(),
  round: __t.u32(),
  momRound: __t.u32(),
  approveRound: __t.u32(),
  approvedBy: __t.option(__t.identity()),
  windowRound: __t.u32(),
});
export type Payment = __Infer<typeof Payment>;

export const ReleaseTimer = __t.object("ReleaseTimer", {
  id: __t.u64(),
  paymentId: __t.u64(),
  round: __t.u32(),
  scheduledAt: __t.scheduleAt(),
});
export type ReleaseTimer = __Infer<typeof ReleaseTimer>;

export const SecretLimit = __t.object("SecretLimit", {
  id: __t.u64(),
  ownerId: __t.identity(),
  dealOrListingId: __t.u64(),
  kind: __t.string(),
  cents: __t.u64(),
});
export type SecretLimit = __Infer<typeof SecretLimit>;

