// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  slot: __t.string(),
  label: __t.string(),
  nessieAccountId: __t.string(),
  balanceCents: __t.u64(),
});
export type Account = __Infer<typeof Account>;

export const AuditEvent = __t.object("AuditEvent", {
  id: __t.u64(),
  text: __t.string(),
  at: __t.u64(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const Deal = __t.object("Deal", {
  id: __t.u64(),
  listingId: __t.u64(),
  buyerId: __t.identity(),
  sellerId: __t.identity(),
  status: __t.string(),
  round: __t.u32(),
  bidCents: __t.u64(),
  askCents: __t.u64(),
  priceCents: __t.option(__t.u64()),
  buyerAccepted: __t.bool(),
  sellerAccepted: __t.bool(),
  shipByAt: __t.option(__t.u64()),
  tracking: __t.option(__t.string()),
  holdTransferId: __t.option(__t.string()),
  releaseTransferId: __t.option(__t.string()),
  refundTransferId: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type Deal = __Infer<typeof Deal>;

export const Listing = __t.object("Listing", {
  id: __t.u64(),
  sellerId: __t.identity(),
  title: __t.string(),
  emoji: __t.string(),
  listCents: __t.u64(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Listing = __Infer<typeof Listing>;

export const Member = __t.object("Member", {
  identity: __t.identity(),
  name: __t.string(),
  role: __t.string(),
  slot: __t.string(),
  online: __t.bool(),
});
export type Member = __Infer<typeof Member>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  dealId: __t.u64(),
  from: __t.string(),
  text: __t.string(),
  cents: __t.option(__t.u64()),
  at: __t.u64(),
});
export type Message = __Infer<typeof Message>;

export const MyLimit = __t.object("MyLimit", {
  kind: __t.string(),
  cents: __t.u64(),
});
export type MyLimit = __Infer<typeof MyLimit>;

export const MyLimits = __t.object("MyLimits", {});
export type MyLimits = __Infer<typeof MyLimits>;

export const NegotiationTickRow = __t.object("NegotiationTickRow", {
  id: __t.u64(),
  dealId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type NegotiationTickRow = __Infer<typeof NegotiationTickRow>;

export const NessieLog = __t.object("NessieLog", {
  id: __t.u64(),
  method: __t.string(),
  path: __t.string(),
  status: __t.u32(),
  note: __t.string(),
  at: __t.u64(),
});
export type NessieLog = __Infer<typeof NessieLog>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  dealId: __t.u64(),
  kind: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type Outbox = __Infer<typeof Outbox>;

export const SecretLimit = __t.object("SecretLimit", {
  id: __t.u64(),
  ownerId: __t.identity(),
  dealOrListingId: __t.u64(),
  kind: __t.string(),
  cents: __t.u64(),
});
export type SecretLimit = __Infer<typeof SecretLimit>;

export const ShipTimer = __t.object("ShipTimer", {
  id: __t.u64(),
  dealId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ShipTimer = __Infer<typeof ShipTimer>;

